"""
이벤트 워크플로우 설정 파일
이벤트 간의 인과관계를 정의합니다.
"""

from actverse_common.events import (
    EVENT_VIDEO_DOWNLOADED,
    EVENT_FRAMES_EXTRACTION_REQUESTED,
    EVENT_FRAMES_EXTRACTED,
    EVENT_LABELING_REQUESTED,
    EVENT_LABELING_COMPLETED,
    EVENT_MODEL_TRAINING_REQUESTED,
    EVENT_MODEL_TRAINING_COMPLETED,
    EVENT_MODEL_DEPLOYMENT_REQUESTED,
    EVENT_MODEL_DEPLOYMENT_COMPLETED,
    EVENT_MODEL_INFERENCE_REQUESTED,
    EVENT_MODEL_INFERENCE_COMPLETED,
    EVENT_TASK_COMPLETED
)

# 이벤트 워크플로우 정의
# 키: 이벤트 타입, 값: 다음에 발행할 이벤트 타입
EVENT_WORKFLOW = {
    EVENT_VIDEO_DOWNLOADED: EVENT_FRAMES_EXTRACTION_REQUESTED,
    EVENT_FRAMES_EXTRACTED: EVENT_LABELING_REQUESTED,
    EVENT_LABELING_COMPLETED: EVENT_MODEL_TRAINING_REQUESTED,
    EVENT_MODEL_TRAINING_COMPLETED: EVENT_MODEL_DEPLOYMENT_REQUESTED,
    EVENT_MODEL_DEPLOYMENT_COMPLETED: EVENT_MODEL_INFERENCE_REQUESTED,
    EVENT_MODEL_INFERENCE_COMPLETED: EVENT_TASK_COMPLETED
} 